dist: trusty

language: go

go:
  - 1.8

script:
  - make
  - docker build -t digitalocean/bind_exporter .
  
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push digitalocean/bind_exporter;
    fi
