---
version: 2.1

orbs:
  prometheus: prometheus/prometheus@0.4.0

executors:
  # Whenever the Go version is updated here, .promu.yml should
  # also be updated.
  golang:
    docker:
    - image: circleci/golang:1.14

jobs:
  test:
    executor: golang

    steps:
    - prometheus/setup_environment
    - run: make
    - prometheus/store_artifact:
        file: bind_exporter

  codespell:
    docker:
    - image: circleci/python

    steps:
    - checkout
    - run: sudo pip install codespell
    - run: codespell --skip=".git,./vendor,ttar,go.mod,go.sum,*pem" -L uint,packages\',uptodate

  publish_master:
    executor: golang

    steps:
    - prometheus/setup_build_environment
    - prometheus/publish_images:
        registry: docker.io
        organization: prometheuscommunity
        login_variable: DOCKER_LOGIN
        password_variable: DOCKER_PASSWORD

  publish_release:
    executor: golang

    steps:
    - prometheus/setup_build_environment
    - run: promu crossbuild tarballs
    - run: promu checksum .tarballs
    - run: promu release .tarballs
    - store_artifacts:
        path: .tarballs
        destination: releases
    - prometheus/publish_release_images:
        registry: docker.io
        organization: prometheuscommunity
        login_variable: DOCKER_LOGIN
        password_variable: DOCKER_PASSWORD

workflows:
  version: 2
  bind_exporter:
    jobs:
    - test:
        filters:
          tags:
            only: /.*/
    - prometheus/build:
        name: build
        filters:
          tags:
            only: /.*/
    - codespell:
        filters:
          tags:
            only: /.*/
    - publish_master:
        context: org-context
        requires:
        - test
        - build
        filters:
          branches:
            only: master
    - publish_release:
        context: org-context
        requires:
        - test
        - build
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
